backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "site/content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "select", options: ["Inverted Axes", "Aaron Roberts", "Mike Pitts", "Ray Fisher", "Mike Pires", "Malcolm Jardine"], default: "Inverted Axes"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "Show Intro Blurb in article?", name: "showblurb", widget: "boolean", required: false}
      - {label: "Featured Image / Thumbnail", name: "image", widget: "image", required: false}
      - {label: "Alternate Thumbnail", name: "thumbnail", widget: "image", required: false}
      - {label: "Thumbnail Horizontal Alignment", name: "halign", widget: "select", options: ["center", "left", "right"], default: "center", required: false}
      - {label: "Thumbnail Vertical Alignment", name: "valign", widget: "select", options: ["center", "top", "bottom"], default: "center", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "about" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "About Post" # Used in the UI, ie.: "New Post"
    folder: "site/content/about" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Order", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: Image A, name: imageUrlA, widget: image}
      - {label: Image B, name: imageUrlB, widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Show stream schedule", name: "schedule", widget: "boolean", default: true}
      # - file: "site/content/about/_index.md"
      #   label: "About Page"
      #   name: "about"
      #   fields:
      #     - {label: Title, name: title, widget: string}
      #     - {label: Image, name: image, widget: image}
      #     - label: About Entries
      #       name: about_entries
      #       widget: list
      #       fields:
      #         - {label: Heading, name: heading, widget: string}
      #         - label: "Author"
      #           name: "author"
      #           widget: "select"
      #           options: ["Inverted Axes", "Aaron Roberts", "Mike Pitts", "Ray Fisher"]
      #           default: "Inverted Axes"
      #         - {label: "Body", name: "body", widget: "markdown"}
      #         - {label: Image A, name: imageUrlA, widget: image}
      #         - {label: Image B, name: imageUrlB, widget: image}
      #         - {label: "Text", name: "text", widget: "text"}
